services:
  db:
    image: mongo:7
    container_name: lms-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./apps/api
    container_name: lms-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://db:27017/lms
      - JWT_SECRET=please_change_me
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "8080:8080"

  web:
    build: ./apps/web
    container_name: lms-frontend
    restart: unless-stopped
    environment:
      - VITE_API_BASE=http://localhost:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mongo_data: